CREATE TYPE user_role AS ENUM (
    'STUDENT',
    'TEACHER',
    'FINANCE_ACCOUNTANT',
    'SYSTEM_ADMIN',
    'STUDENT_AFFAIRS_ADMIN',
    'RECTOR_PRO_RECTOR'
);

CREATE TYPE registration_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE financial_type AS ENUM ('SALARY', 'SCHOLARSHIP', 'STIPEND', 'TUITION_FEE');
CREATE TYPE financial_status AS ENUM ('PENDING', 'APPROVED', 'PAID', 'REJECTED');
